### ISSUE TITLE
参数类型错误

### ISSUE THREAD

**Issue by yyrdl** [iCGY96/Model-Pivot#2]
https://github.com/iCGY96/open-exchange/blob/master/restapi/app.py#L99
```python
  try:
                parser = pt.PytorchParser(params['model_file_path'], params['input_shape'])
                parser.run(params['output_path'])
            except:
                return make_response(jsonify({'error': 'An error occurred during the conversion!'}), 401)

```
这里的input_shape 传入的是一个元组，实际应该是一个数组 `[3,244,244]`
参考： https://github.com/iCGY96/open-exchange/blob/master/test/test_pytorch.py#L16

这个bug 修复后可以调通 PyTorch 转 IR ，IR 转 Pytorch 还在debug中

**Comment by gary23ai** [comment]
感谢！
